baseURL: https://www.joshklop.com
title: Josh Klopfenstein
theme: github.com/LukasJoswiak/etch
languageCode: en-US
params:
  description: My internet home
  copyright: Copyright © 2023 Josh Klopfenstein
  dark: auto
  highlight: true
menu:
  main:
    - identifier: posts
      name: posts
      title: posts
      url: /
      weight: 10
    - identifier: about
      name: about
      title: about
      url: /about/
      weight: 20
    - identifier: github
      name: github
      url: https://github.com/joshklop
      weight: 30
permalinks:
  posts: /:title/
markup:
  tableOfContents:
    ordered: true
  highlight:
    style: tango
