baseURL: https://www.joshklop.com
title: Josh Klopfenstein
theme: github.com/LukasJoswiak/etch
languageCode: en-US
params:
  description: My internet home
  name: Josh Klopfenstein
  since: 2023
  dark: auto
  highlight: true
menu:
  main:
    - identifier: about
      name: about
      title: about
      url: /about/
      weight: 1
    - identifier: github
      name: github
      url: https://github.com/joshklop
      weight: 2
permalinks:
  posts: /:title/
markup:
  tableOfContents:
    ordered: true
  highlight:
    style: tango
